apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGFrb2MxN3Bj
  CLOUDINARY_KEY: Mzg5NDI1NjY5OTM2MjUz
  CLOUDINARY_SECRET: QnotR01IajZIclpOa0F5NnFWR1RVbHB5Y21B
  MAPBOX_TOKEN: cGsuZXlKMUlqb2libWxvWVc1MGFERTVNRFV3TUNJc0ltRWlPaUpqYldsbE9EZ3dhREl3TURCek0yTnpaR1JwYmpGbE56TjFJbjAubXF4M2lxSGJCNWRWSkgwbWsyN3B4dw==
  DB_URL: bW9uZ29kYitzcnY6Ly9uaWhhbnRocmVkZHkxOTA1MDBfZGJfdXNlcjpnaWNIQlhTS1pOSmRlRWNZQGNsdXN0ZXIwLmphdWRndG4ubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  SECRET: bmloYW50aA==
